pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - ocean.pangeo.io
        letsencrypt:
          contactEmail: raphael.dussin@gmail.com
      service:
        loadBalancerIP: 34.66.6.21
    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://ocean.pangeo.io/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-ocean-prod-dask-gateway.ocean-prod:80"
    hub:
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: "http://traefik-ocean-prod-dask-gateway.ocean-prod"
