pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - staging.ocean.pangeo.io
        letsencrypt:
          contactEmail: raphael.dussin@gmail.com
      service:
        loadBalancerIP: 35.238.36.78
    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 0.25Gi
    scheduling:
      userScheduler:
        enabled: false
    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://staging.ocean.pangeo.io/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-ocean-staging-dask-gateway.ocean-staging:80"
    hub:
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: "http://traefik-ocean-staging-dask-gateway.ocean-staging"
