daskhub:
  jupyterhub:
    scheduling:
      userScheduler:
        enabled: true
      #userPods:
        #nodeAffinity:
        #  matchNodePurpose: require
      #corePods:
        #nodeAffinity:
          #matchNodePurpose: require
    singleuser:
      #nodeSelector: {agentpool: notebook}
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: home
            mountPath: /home/jovyan
            subPath: "home/{username}"
      storage:
        type: static
        static:
          pvcName: home-nfs
          subPath: "home/{username}"
        homeMountPath: /home/jovyan
      cloudMetadata:
        enabled: false
      cpu:
        limit: 0.8
        guarantee: 0.4
      memory:
        limit: 2.5G
        guarantee: 1.25G
    prePuller:
      continuous:
        enabled: false
    hub:
      #nodeSelector: {agentpool: nodepool1}
      resources:
        requests:
          cpu: 0.4
          memory: 1.25G
        limits:
          cpu: 0.8
          memory: 2.5G
      image:
        tag: "0.10.0-beta.1"
      extraConfig:
        azure: |
          c.KubeSpawner.start_timeout = 60 * 20 # 20-minute timeout for Azure (!)
        profile_list: |
          c.KubeSpawner.profile_list = [
            {
                'display_name': 'minimal (0.2 Cores, 0.625 GB RAM)',
                'kubespawner_override': {
                    'cpu_limit': 0.4,
                    'cpu_guarantee': 0.2,
                    'mem_limit': '1.25G',
                    'mem_guarantee': '0.625G',
                }
            },
            {
                'display_name': 'small (0.4 Cores, 1.25 GB RAM)',
                'kubespawner_override': {
                    'cpu_limit': 0.8,
                    'cpu_guarantee': 0.4,
                    'mem_limit': '2.5G',
                    'mem_guarantee': '1.25G',
                }
            },
            {
                'display_name': 'medium (0.8 Cores, 2.5 GB RAM)',
                'kubespawner_override': {
                    'cpu_limit': 1.6,
                    'cpu_guarantee': 0.8,
                    'mem_limit': '5G',
                    'mem_guarantee': '2.5G',
                }
            },
            {
                'display_name': 'large (1.6 Cores, 5 GB RAM)',
                'kubespawner_override': {
                    'cpu_limit': 3.2,
                    'cpu_guarantee': 1.6,
                    'mem_limit': '10G',
                    'mem_guarantee': '5G',
                }
            }
          ]
        customPodHook: |
          c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
          c.JupyterHub.template_vars = {
            'pangeo_hub_title': 'ooi.pangeo.io',
            'pangeo_hub_subtitle': 'a community hub for geoscience research using OOI data',
            'pangeo_welcome': """Welcome to ooi.pangeo.io. This Pangeo deployment lives in Azure Cloud region <code>eastus</code>. It is maintained by the <a href="http://pangeo.io">Pangeo project</a> and is supported by a grant from Microsoft and the National Science Foundation. The hub's configuration is stored in the github repository <a href="https://github.com/pangeo-data/pangeo-cloud-federation/">https://github.com/pangeo-data/pangeo-cloud-federation/</a>. To provide feedback and report any technical problems, please use the <a href="https://github.com/pangeo-data/pangeo-cloud-federation/issues">this GitHub issue tracker</a>. To discuss OOI-specific issues related to this Pangeo deployment, please use the <a href="https://github.com/ooicloud/ooi-pangeo/issues">OOI Pangeo GitHub issue tracker</a>."""
          }
      extraVolumes:
        - name: custom-templates
          gitRepo:
            repository: "https://github.com/pangeo-data/pangeo-custom-jupyterhub-templates.git"
            revision: "0c799bb2f880c8b516dcf90e2a90328078d60c25"
      extraVolumeMounts:
        - mountPath: /usr/local/share/jupyterhub/custom_templates
          name: custom-templates
          subPath: "pangeo-custom-jupyterhub-templates/templates"
        - mountPath: /usr/local/share/jupyterhub/static/extra-assets
          name: custom-templates
          subPath: "pangeo-custom-jupyterhub-templates/extra-assets"
    auth:
      type: github
      github:
        orgWhitelist:
          - ooicloud
      scopes:
        - "read:org"
        - "read:user"
      admin:
        access: true
        users:
          - daxsoule
          - jhamman
          - mrocklin
          - rabernat
          - scottyhq
          - tjcrone
          - yuvipanda

homeDirectories:
  nfs:
    enabled: true
    serverPath: "/mnt/ooicloud"
    serverIP: 10.0.0.4
