pangeo:
  jupyterhub:
    scheduling:
      userPods:
        nodeAffinity:
          matchNodePurpose: require
      corePods:
        nodeAffinity:
          matchNodePurpose: require
    singleuser:
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command:
            - "sh"
            - "-c"
            - >
              id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan ;
              id && chown 1000:1000 /srv/shared && ls -lhd /srv/shared ;
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: home
              mountPath: /home/jovyan
              subPath: "esip.pangeo.io/home/{username}"
              # Alternatively, ssh into node and chown once
            - name: jupyterhub-shared
              mountPath: /srv/shared
              subPath: "esip.pangeo.io/shared"
      extraVolumes:
        - name: jupyterhub-shared
          persistentVolumeClaim:
            claimName: data-nfs
      storage:
        type: static
        static:
          pvcName: home-nfs
          subPath: "esip.pangeo.io/home/{username}"
        #requires having run config/shared--nfs.yaml
        extraVolumeMounts:
          - name: jupyterhub-shared
            mountPath: /srv/shared
            subPath: "esip.pangeo.io/shared"
        extraVolumes:
          - name: jupyterhub-shared
            persistentVolumeClaim:
              claimName: shared-nfs

      cloudMetadata:
        enabled: true
      cpu:
        limit: 4
        guarantee: 3
      memory:
        limit: 16G
        guarantee: 14G
      profileList:
        - display_name: "Default environment (m5.2xlarge | 4 cores, 16Gb)"
          description: "ESIP environment extending pangeo base-notebook"
          default: true
        - display_name: "Pangeo-notebook (m5.2xlarge | 4 cores, 16Gb)"
          description: "2019.08.08 pangeo-notebook from pangeo-stacks"
          kubespawner_override:
            image: pangeo/pangeo-notebook:2019.08.08
        - display_name: "Base-notebook (m5.2xlarge | 4 cores, 16Gb)"
          description: "2019.08.08 base-notebook from pangeo-stacks"
          kubespawner_override:
            image: pangeo/base-notebook:2019.08.08
    auth:
      github:
        orgWhitelist:
          - "ESIPFed"
          - "pangeo-data"
          - "cdi-workshops"
      scopes:
        - "read:user"
        - "user:email"
        - "read:org"
      admin:
        access: true
        users:
          - scottyhq
          - rsignell-usgs
    hub:
      resources:
        requests:
          cpu: 0.45
          memory: 1G
        limits:
          cpu: 1.25
          memory: 2G
      extraConfig:
        cloneRepo: |
          # Hack solution for branding
          import os, shutil
          repo = 'https://github.com/scottyhq/nasa-pangeo-style-template'
          webdir = '/usr/local/share/jupyterhub/static'
          dst = '/srv/jupyterhub/style'
          shutil.rmtree(dst, ignore_errors=True)
          os.system(f'git clone {repo} {dst}')
          os.system(f'cp -rf {dst}/extra-assets {webdir}')
        customPodHook: |
          c.JupyterHub.template_paths = ['/srv/jupyterhub/style/templates']
          c.JupyterHub.template_vars = {
            'pangeo_hub_title': 'esip.pangeo.io',
            'pangeo_hub_subtitle': 'a community hub for ESIP',
            'pangeo_welcome': """Welcome to esip.pangeo.io! This hub lives in AWS region <code>us-west-2</code>. It is maintained by the <a href="http://pangeo.io">Pangeo project</a> and is supported by <a href="https://github.com/pangeo-data/nasa-access-17">NASA Grant #17-ACCESS17-0003</a> and cloud credits from Amazon. Access is currently limited to the <a href="https://github.com/pangeo-data">Pangeo GitHub Organization</a>. The hub's configuration is stored in this <a href="https://github.com/pangeo-data/pangeo-cloud-federation/">github repository</a>. To provide feedback and report any technical problems, please use the <a href="https://github.com/pangeo-data/pangeo-cloud-federation/issues">github issue tracker</a>."""
          }
      extraVolumes:
        - name: custom-assets
          emptyDir: {}
      extraVolumeMounts:
        - name: custom-assets
          mountPath: /usr/local/share/jupyterhub/static/extra-assets


homeDirectories:
 nfs:
   enabled: true
   serverIP: fs-699c01c2.efs.us-west-2.amazonaws.com
