name: nasa
channels:
  - conda-forge
dependencies:
  - python=3.7
  - ipykernel=5.1
  - nb_conda_kernels=2.2
  - fsspec=0.3
  - s3fs=0.3
  - gcsfs=0.3
  - intake=0.5
  - intake-xarray=0.3
  - xarray=0.12
  - zarr=2.3
  - h5py=2.9
  - h5netcdf=0.7
  - dask=2.1
  - distributed=2.1
  - dask-kubernetes=0.9
  - matplotlib=3.1
  - jupyter=1.0
  - jupyter-server-proxy=1.1
  - ipywidgets=7.5
  - graphviz=2.40
  - jupyterlab=1.0
  - jupyterhub=1.0
  - libgdal=2.4
  - boto3=1.9
  - awscli=1.16
  - hvplot=0.4
  - geoviews-core=1.6
  - ipyleaflet=0.11
  - datashader=0.7
  - requests=2.22
  - pandas=0.25
  - geopandas=0.5
  - rasterio=1.0
  - rio-cogeo=1.1
  - sat-search=0.2
  - sat-stac
  - nbgitpuller=0.6
  - pip=19.2
  - pip:
    - dask-labextension==0.3.1
    - git+https://github.com/pangeo-data/intake-stac.git
