daskhub:
  jupyterhub:
    proxy:
      https:
        hosts:
          - us-central1-b.gcp.pangeo.io
        letsencrypt:
          contactEmail: rpa@ldeo.columbia.edu
      service:
        loadBalancerIP: 35.238.103.127
    hub:
      extraEnv:
        OAUTH_CALLBACK_URL: "https://us-central1-b.gcp.pangeo.io/hub/oauth_callback"

prometheus-operator:
  enabled: false  # handled in staging
  # I don't understand why these pods are showing up in the first place,
  # when we've disabled them
  grafana:
    enabled: false
  prometheus:
    enabled: false
  kube-state-metrics:
    enabled: false
