daskhub:
  jupyterhub:
    proxy:
      https:
        hosts:
          - us-central1-b.gcp.pangeo.io
        letsencrypt:
          contactEmail: rpa@ldeo.columbia.edu
      service:
        loadBalancerIP: 35.238.103.127
    hub:
      extraEnv:
        OAUTH_CALLBACK_URL: "https://us-central1-b.gcp.pangeo.io/hub/oauth_callback"

  dask-gateway:
    gateway:
      backend:
        # Ensure the scheduler and worker pods end up on 
        # nodes that are already being used, to avoid scheduling on nodes
        # that would otherwise be reclaimed by the cluster autoscaler.
        scheduler:
          extraPodConfig:
            schedulerName: gcp-uscentral1b-prod-user-scheduler
        worker:
          extraPodConfig:
            schedulerName: gcp-uscentral1b-prod-user-scheduler
