daskhub:
  jupyterhub:
    proxy:
      https:
        hosts:
          - staging.us-central1-b.gcp.pangeo.io
        letsencrypt:
          contactEmail: rpa@ldeo.columbia.edu 
      service:
        loadBalancerIP: 34.69.173.244
    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 0.25Gi
        limits:
          cpu: "0.1"
          memory: 0.25Gi
    scheduling:
      userScheduler:
        enabled: false
  dask-gateway:
    gateway:
      backend:
        # Ensure the scheduler and worker pods end up on
        # nodes that are already being used, to avoid scheduling on nodes
        # that would otherwise be reclaimed by the cluster autoscaler.
        scheduler:
          extraPodConfig:
            schedulerName: gcp-uscentral1b-staging-user-scheduler
        worker:
          extraPodConfig:
            schedulerName: gcp-uscentral1b-staging-user-scheduler

metrics:
  enabled: true

ingress-nginx:
  controller:
    service:
      loadBalancerIP: "34.121.206.128"
