daskhub:
  jupyterhub:
    proxy:
      https:
        hosts:
          - staging.us-central1-b.gcp.pangeo.io
        letsencrypt:
          contactEmail: rpa@ldeo.columbia.edu 
      service:
        loadBalancerIP: 34.69.173.244
    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 0.25Gi
        limits:
          cpu: "0.1"
          memory: 0.25Gi
    scheduling:
      userScheduler:
        enabled: false

metrics:
  enabled: true

prometheus-operator:
  grafana:
    server:
      domain: "grafana.us-central1-b.gcp.pangeo.io"
    ingress:
      hosts:
        - "grafana.us-central1-b.gcp.pangeo.io"

ingress-nginx:
  controller:
    service:
      loadBalancerIP: "34.121.206.128"
