daskhub:
  jupyterhub:
    proxy:
      https:
        hosts:
          - staging.us-central1-b.gcp.pangeo.io
        letsencrypt:
          contactEmail: rpa@ldeo.columbia.edu 
      service:
        loadBalancerIP: 34.69.173.244
    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 0.25Gi
        limits:
          cpu: "0.1"
          memory: 0.25Gi
    scheduling:
      userScheduler:
        enabled: false

metrics:
  enabled: true

prometheus-operator:
  prometheusOperator:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: hub.jupyter.org/node-purpose
              operator: In
              values:
              - core

  grafana:
    server:
      domain: "grafana.us-central1-b.gcp.pangeo.io"
    ingress:
      hosts:
        - "grafana.us-central1-b.gcp.pangeo.io"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: hub.jupyter.org/node-purpose
              operator: In
              values:
              - core
  prometheus:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: hub.jupyter.org/node-purpose
              operator: In
              values:
              - core
  kube-state-metrics:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: hub.jupyter.org/node-purpose
              operator: In
              values:
              - core

ingress-nginx:
  controller:
    service:
      loadBalancerIP: "34.121.206.128"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: hub.jupyter.org/node-purpose
              operator: In
              values:
              - core


