pangeo:
  jupyterhub:
    scheduling:
      userPods:
        nodeAffinity:
          matchNodePurpose: require
      corePods:
        nodeAffinity:
          matchNodePurpose: require
    singleuser:
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command:
            - "sh"
            - "-c"
            - >
              id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan ;
              id && chown 1000:1000 /srv/shared && ls -lhd /srv/shared ;
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: home
              mountPath: /home/jovyan
              subPath: "home/icesat2.pangeo.io/{username}"
            - name: jupyterhub-shared
              mountPath: /srv/shared
              subPath: "icesat2.pangeo.io/shared"
      extraVolumes:
        - name: jupyterhub-shared
          persistentVolumeClaim:
            claimName: data-nfs
      storage:
        type: static
        static:
          pvcName: home-nfs
          subPath: "home/icesat2.pangeo.io/{username}"
        #requires having run config/shared--nfs.yaml
        extraVolumeMounts:
          - name: jupyterhub-shared
            mountPath: /srv/shared
            subPath: "icesat2.pangeo.io/shared"
        extraVolumes:
          - name: jupyterhub-shared
            persistentVolumeClaim:
              claimName: shared-nfs
      cloudMetadata:
        enabled: true
      cpu:
        limit: 4
        guarantee: 3
      memory:
        limit: 16G
        guarantee: 14G
      profileList:
        - display_name: "Default environment (m5.2xlarge | 4 cores, 16Gb)"
          description: "Updated environment defined in pangeo-cloud-federation"
          default: true
        - display_name: "IceSat-2 Hackweek 2019 Image (m5.2xlarge | 4 cores, 16Gb)"
          description: "Copy of IceSat-2 Hackweek environment"
          kubespawner_override:
            image: uwhackweeks/icesat2:2019
        - display_name: "GeoHackWeek 2019 (m5.2xlarge | 4 cores, 16Gb)"
          description: "GeoHackWeek 2019 conda environment"
          kubespawner_override:
            image: scottyhq/geohackweek2019:latest
        - display_name: "Latest Pangeo-notebook Image (m5.2xlarge | 4 cores, 16Gb)"
          description: "The latest build of pangeo/pangeo-notebook"
          kubespawner_override:
            image: pangeo/pangeo-notebook:latest
    auth:
      github:
        orgWhitelist:
          - "escience-pangeo"
          - "geohackweek"
          - "ICESAT-2HackWeek"
          - "pangeo-data"
      scopes:
        - "read:user"
        - "user:email"
        - "read:org"
      admin:
        access: true
        users:
          - scottyhq
          - jhamman
          - apawloski
          - amanda-tan
    hub:
      resources:
        requests:
          cpu: 0.45
          memory: 1G
        limits:
          cpu: 1.25
          memory: 2G
      extraConfig:
        cloneRepo: |
          # Hack solution for branding
          import os, shutil
          repo = 'https://github.com/scottyhq/pangeo-custom-jupyterhub-templates'
          webdir = '/usr/local/share/jupyterhub/static'
          dst = '/srv/jupyterhub/style'
          shutil.rmtree(dst, ignore_errors=True)
          os.system(f'git clone {repo} {dst}')
          os.system(f'cp -rf {dst}/extra-assets {webdir}')
        customPodHook: |
          c.JupyterHub.template_paths = ['/srv/jupyterhub/style/templates']
          c.JupyterHub.template_vars = {
            'pangeo_hub_title': 'icesat2.pangeo.io',
            'pangeo_hub_subtitle': 'a community hub for icesat2 hackweek',
            'pangeo_welcome': """Welcome to icesat2.pangeo.io, the computational environment for <a href="https://icesat-2hackweek.github.io">Icesat-2 Hackweek</a>! This hub lives in AWS region <code>us-west-2</code>. It is maintained by the <a href="http://pangeo.io">Pangeo project</a> and is supported by <a href="https://github.com/pangeo-data/nasa-access-17">NASA Grant #17-ACCESS17-0003</a> and cloud credits from Amazon. Access is currently limited to the <a href="https://github.com/ICESAT-2HackWeek">ICESAT-2HackWeek GitHub Organization</a>. The hub's configuration is stored in this <a href="https://github.com/pangeo-data/pangeo-cloud-federation/">github repository</a>. To provide feedback and report any technical problems, please use the <a href="https://github.com/pangeo-data/pangeo-cloud-federation/issues">github issue tracker</a>."""
          }
      extraVolumes:
        - name: custom-assets
          emptyDir: {}
      extraVolumeMounts:
        - name: custom-assets
          mountPath: /usr/local/share/jupyterhub/static/extra-assets

homeDirectories:
  nfs:
    enabled: true
    serverIP: fs-04b8a8ac.efs.us-west-2.amazonaws.com
