pangeo:
  jupyterhub:
    scheduling:
      userPods:
        nodeAffinity:
          matchNodePurpose: require
      corePods:
        nodeAffinity:
          matchNodePurpose: require
    # until resolved: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1393
    prePuller:
      continuous:
        enabled: false
    singleuser:
      profileList:
        - display_name: "Standard environment"
          description: "https://github.com/pangeo-data/pangeo-cloud-federation/tree/staging/deployments/icesat2/image/binder"
          default: true
        - display_name: "ICESat-2 Hackweek 2020"
          description: "https://github.com/ICESAT-2HackWeek/jupyter-image-2020"
          kubespawner_override:
            image: uwhackweeks/icesat2:latest
        - display_name: "Latest Pangeo-notebook"
          description: "https://github.com/pangeo-data/pangeo-docker-images/tree/master/pangeo-notebook"
          kubespawner_override:
            image: pangeo/pangeo-notebook:latest
        - display_name: "Latest Base-notebook"
          description: "https://github.com/pangeo-data/pangeo-docker-images/tree/master/base-notebook"
          kubespawner_override:
            image: pangeo/base-notebook:latest
        - display_name: "Latest ML-notebook"
          description: "https://github.com/pangeo-data/pangeo-docker-images/tree/master/ml-notebook"
          kubespawner_override:
            image: pangeo/ml-notebook:latest
            mem_limit: 60G
            mem_guarantee: 25G
            environment: {'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility'}
            tolerations: [{'key': 'nvidia.com/gpu','operator': 'Equal','value': 'present','effect': 'NoSchedule'}]
            extra_resource_limits: {"nvidia.com/gpu": "1"}
      startTimeout: 600
      initContainers:
        - name: change-volume-mount-permissions
          image: busybox
          command:
            - "sh"
            - "-c"
            - >
              id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan ;
              id && chown 1000:1000 /srv/shared && ls -lhd /srv/shared ;
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: home
              mountPath: /home/jovyan
              subPath: "home/icesat2.pangeo.io/{username}"
            - name: jupyterhub-shared
              mountPath: /srv/shared
              subPath: "icesat2.pangeo.io/shared"
      extraEnv:
        PANGEO_SCRATCH_PREFIX: "s3://pangeo-scratch"

      storage:
        type: static
        static:
          pvcName: home-nfs
          subPath: "home/icesat2.pangeo.io/{username}"
        #requires having run config/shared--nfs.yaml
        extraVolumeMounts:
          - name: jupyterhub-shared
            mountPath: /srv/shared
            subPath: "icesat2.pangeo.io/shared"
        extraVolumes:
          - name: jupyterhub-shared
            persistentVolumeClaim:
              claimName: shared-nfs
      cloudMetadata:
        enabled: true
      cpu:
        guarantee: 2
        limit: 4
      memory:
        guarantee: 7G
        limit: 7G

    hub:
      resources:
        requests:
          cpu: 0.5
          memory: 1G
        limits:
          cpu: 1.25
          memory: 2G
      initContainers:
        - name: git-clone-templates
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --branch=master
            - --depth=1
            - --
            - https://github.com/scottyhq/pangeo-custom-jupyterhub-templates.git
            - /mnt/template-repo
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: custom-templates
              mountPath: /mnt/template-repo
      extraVolumes:
        - name: custom-templates
          emptyDir: {}
      extraVolumeMounts:
        # Note: subPath is relative to repo root dir
        - name: custom-templates
          mountPath: /usr/local/share/jupyterhub/custom-templates
          subPath: templates
        - name: custom-templates
          mountPath: /usr/local/share/jupyterhub/static/extra-assets
          subPath: extra-assets
      extraConfig:
        00-template-config: |
          c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom-templates/']
          c.JupyterHub.template_vars = {
            'pangeo_hub_title': 'Pangeo Cloud',
            'pangeo_hub_subtitle': 'aws-uswest.pangeo.io',
            'pangeo_welcome': """Welcome to Pangeo Cloud! This JupyterHub lives in the AWS Cloud region <code>us-west-2</code>. It is maintained by the <a href="http://pangeo.io">Pangeo project</a> and is supported by <a href="https://github.com/pangeo-data/nasa-access-17">NASA Grant #17-ACCESS17-0003</a> and cloud credits from Amazon. For information and signup instructions, please visit the <a href="http://pangeo.io/cloud.html">Pangeo Cloud Website</a>. <strong>This is a prototype and should be treated accordingly. We make no promises that the hub will remain active. Do not store passwords or sensitive data in your home directory</strong>."""
          }
      extraEnv:
        OAUTH2_AUTHORIZE_URL: "https://pangeo.auth0.com/authorize"
        OAUTH2_TOKEN_URL: "https://pangeo.auth0.com/oauth/token"

    auth:
      type: custom
      custom:
        className: oauthenticator.generic.GenericOAuthenticator
        config:
          login_service: "Pangeo Login"
          token_url: https://pangeo.auth0.com/oauth/token
          userdata_url: https://pangeo.auth0.com/oauth/userinfo
          userdata_method: GET
          username_key: nickname
          scope:
            - openid
            - profile
            - email
      admin:
        access: true
        users:
          - scottyhq
          - salvis2


  dask-gateway:
     gateway:
       backend:
         scheduler:
         # optimized for t3.medium nodegroup
           cores:
             request: 0.8
             limit: 1
           memory:
             request: 1G
             limit: 2G

homeDirectories:
  nfs:
    enabled: true
    serverPath: "/homes"
    serverIP: fs-04b8a8ac.efs.us-west-2.amazonaws.com
    serverName: pangeo-efs
