pangeo:
  jupyterhub:
    scheduling:
      userPods:
        nodeAffinity:
          matchNodePurpose: require
      corePods:
        nodeAffinity:
          matchNodePurpose: require
    # until resolved: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1393
    prePuller:
      continuous:
        enabled: false
    singleuser:
      startTimeout: 600
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command:
            - "sh"
            - "-c"
            - >
              id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan ;
              id && chown 1000:1000 /srv/shared && ls -lhd /srv/shared ;
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: home
              mountPath: /home/jovyan
              subPath: "home/icesat2.pangeo.io/{username}"
            - name: jupyterhub-shared
              mountPath: /srv/shared
              subPath: "icesat2.pangeo.io/shared"
      extraVolumes:
        - name: jupyterhub-shared
          persistentVolumeClaim:
            claimName: data-nfs
      storage:
        type: static
        static:
          pvcName: home-nfs
          subPath: "home/icesat2.pangeo.io/{username}"
        #requires having run config/shared--nfs.yaml
        extraVolumeMounts:
          - name: jupyterhub-shared
            mountPath: /srv/shared
            subPath: "icesat2.pangeo.io/shared"
        extraVolumes:
          - name: jupyterhub-shared
            persistentVolumeClaim:
              claimName: shared-nfs
      cloudMetadata:
        enabled: true
      cpu:
        limit: 4
        guarantee: 3
      memory:
        limit: 16G
        guarantee: 14G
    auth:
      github:
        orgWhitelist:
          - "escience-pangeo"
          - "geohackweek"
          - "ICESAT-2HackWeek"
          - "pangeo-data"
      scopes:
        - "read:user"
        - "user:email"
        - "read:org"
      admin:
        access: true
        users:
          - scottyhq
          - jhamman
          - apawloski
          - amanda-tan
    hub:
      resources:
        requests:
          cpu: 0.45
          memory: 1G
        limits:
          cpu: 1.25
          memory: 2G
      extraConfig:
        profileList: |
          c.KubeSpawner.profile_list = [
            {
                'display_name': 'Default environment (4 vCPU, 16 Gb RAM)',
                'default': 'true',
            },
            {
                'display_name': 'IceSat-2 Hackweek 2020 (4 vCPU, 16 Gb RAM)',
                'kubespawner_override': {
                    'image': 'uwhackweeks/icesat2:latest',
                }
            },
            {
                'display_name': 'GeoHackweek 2019 (4 vCPU, 16 Gb RAM)',
                'kubespawner_override': {
                    'image': 'scottyhq/geohackweek2019:latest',
                }
            },
            {
                'display_name': 'IceSat-2 Hackweek 2019 (4 vCPU, 16 Gb RAM)',
                'kubespawner_override': {
                    'image': 'uwhackweeks/icesat2:2019',
                }
            },
            {
                'display_name': 'Latest Pangeo-notebook Image (4 vCPU, 16 Gb RAM)',
                'kubespawner_override': {
                    'image': 'pangeo/pangeo-notebook:latest',
                }
            },
            {
                'display_name': 'Latest Pangeo-base Image (4 vCPU, 16 Gb RAM)',
                'kubespawner_override': {
                    'image': 'pangeo/base-notebook:latest',
                }
            },
            {
                'display_name': 'AmesStereoPipeline *experimental* (4 vCPU, 16 Gb RAM)',
                'kubespawner_override': {
                    'image': 'pangeo/pangeo-notebook:latest',
                }
            },
            {
                'display_name': 'ESIP Environment (4 vCPU, 16 Gb RAM)',
                'kubespawner_override': {
                    'image': 'pangeo/pangeo-esip:latest',
                }
            },
            {
                'display_name': 'Pangeo ML Env (experimental)',
                'kubespawner_override': {
                    'mem_limit': '60G',
                    'mem_guarantee': '25G',
                    'image': 'pangeo/pangeo-ml:latest',
                    'environment': {'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility'},
                    'tolerations': [{'key': 'nvidia.com/gpu','operator': 'Equal','value': 'present','effect': 'NoSchedule'}],
                    'extra_resource_limits': {"nvidia.com/gpu": "1"}
                }
            },
            ]
        cloneRepo: |
          # Hack solution for branding
          import os, shutil
          repo = 'https://github.com/scottyhq/pangeo-custom-jupyterhub-templates'
          webdir = '/usr/local/share/jupyterhub/static'
          dst = '/srv/jupyterhub/style'
          shutil.rmtree(dst, ignore_errors=True)
          os.system(f'git clone {repo} {dst}')
          os.system(f'cp -rf {dst}/extra-assets {webdir}')
        customPodHook: |
          c.JupyterHub.template_paths = ['/srv/jupyterhub/style/templates']
          c.JupyterHub.template_vars = {
            'pangeo_hub_title': 'aws-uswest.pangeo.io',
            'pangeo_hub_subtitle': 'a community hub for the pangeo project',
            'pangeo_welcome': """Welcome to aws-uswest2.pangeo.io, the computational environment for <a href="https://icesat-2hackweek.github.io">Icesat-2 Hackweek</a>! This hub lives in AWS region <code>us-west-2</code>. It is maintained by the <a href="http://pangeo.io">Pangeo project</a> and is supported by <a href="https://github.com/pangeo-data/nasa-access-17">NASA Grant #17-ACCESS17-0003</a> and cloud credits from Amazon. <strong>This is a prototype and should be treated accordingly. We make no promises that the hub will remain active. Do not store passwords or sensitive data in your home directory</strong> Access is currently limited to the <a href="https://github.com/pangeo-data">Pangeo GitHub Organization members</a>. To provide feedback and report any technical problems, please use the <a href="https://github.com/pangeo-data/pangeo-cloud-federation/issues">github issue tracker</a>."""
          }
      extraVolumes:
        - name: custom-assets
          emptyDir: {}
      extraVolumeMounts:
        - name: custom-assets
          mountPath: /usr/local/share/jupyterhub/static/extra-assets

homeDirectories:
  nfs:
    enabled: true
    serverPath: "/homes"
    serverIP: fs-04b8a8ac.efs.us-west-2.amazonaws.com
    serverName: pangeo-efs
