# Leave commented for first build, then uncomment and add loadBalancerIP
daskhub:
  jupyterhub:
    hub:
      extraEnv:
        OAUTH_CALLBACK_URL: "https://aws-uswest2.pangeo.io/hub/oauth_callback"
    singleuser:
      profileList:
        - display_name: "Latest Pangeo-notebook"
          description: "https://github.com/pangeo-data/pangeo-docker-images/releases"
          kubespawner_override:
            image: pangeo/pangeo-notebook:latest
        - display_name: "Latest Base-notebook"
          description: "https://github.com/pangeo-data/pangeo-docker-images/releases"
          kubespawner_override:
            image: pangeo/base-notebook:latest
        - display_name: "Latest ML-notebook"
          description: "https://github.com/pangeo-data/pangeo-docker-images/releases"
          kubespawner_override:
            image: pangeo/ml-notebook:latest
            mem_limit: 60G
            mem_guarantee: 25G
            environment: {'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility'}
            tolerations: [{'key': 'nvidia.com/gpu','operator': 'Equal','value': 'present','effect': 'NoSchedule'}]
            extra_resource_limits: {"nvidia.com/gpu": "1"}
        - display_name: "ICESat-2 Hackweek 2020"
          description: "https://github.com/ICESAT-2HackWeek/jupyter-image-2020"
          kubespawner_override:
            image: uwhackweeks/icesat2:latest
    proxy:
      https:
        hosts:
          - aws-uswest2.pangeo.io
        letsencrypt:
          contactEmail: scottyh@uw.edu

prometheus-operator:
  enabled: false  # handled in staging
  grafana:
    enabled: false
  prometheus:
    enabled: false
