# This configuration is necessary to mount an nfs shared data folder for all users
# kubectl apply -f shared-nfs-staging.yaml --namespace icesat2-staging
apiVersion: v1
kind: PersistentVolume
metadata:
  name: icesat2-staging-shared-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  # mountOptions:
  #   - dir_mode=0777
  #   - file_mode=0777
  #   - uid=1000
  #   - gid=1000
  nfs:
    server: fs-04b8a8ac.efs.us-west-2.amazonaws.com
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-nfs
spec:
  accessModes:
    - ReadWriteMany
  # Match name of PV
  volumeName: icesat2-staging-shared-nfs
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
