name: pangeo
channels:
  - conda-forge
dependencies:
  - dask-gateway==0.7.1
  - cc-plugin-ncei==2.0.2
  - ciso==0.1.0
  - compliance-checker
  - ctd==1.0.0
  - geolinks==0.2.0
  - gridgeo==1.5.2
  - ioos-tools==1.4.0
  - nc-time-axis==1.2.0
  - pocean-core==1.9.3
  - podaacpy==2.4.0
  - pyarrow==0.15.1
  - pyoos==0.8.4
  - python=3.7.3
  - retrying==1.3.3
  - unyt==2.6.0
  - utide==0.2.5
  - xlrd==1.2.0
  - xgcm==0.3.0
  - nbdime==1.1.0
  - xlayers==0.2
  # help the conda solver
  - cartopy==0.17.0
  - dask==2.9.0
  - fiona==1.8.6
  - ipython==7.10.1
  - netcdf4==1.5.1.2
  - numpy==1.17.3
  - pandas=0.25.3
  - scikit-learn==0.22
  - scipy==1.3.2
  - setuptools==42.0.2
  - xarray==0.14.1
  - pip
  - pip:
    - git+https://github.com/intake/filesystem_spec.git@master
    - git+https://github.com/dask/gcsfs.git@master
    - git+https://github.com/intake/gdrivefs.git@master
    - git+https://github.com/NCAR/intake-esm.git
    - git+https://github.com/MITgcm/xmitgcm.git
    - git+https://github.com/xgcm/fastjmd95.git
