pangeo:
  jupyterhub:
    scheduling:
      userPods:
        nodeAffinity:
          matchNodePurpose: require
      corePods:
        nodeAffinity:
          matchNodePurpose: require
    singleuser:
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: home
            mountPath: /home/jovyan
            subPath: "home/hub.pangeo.io/{username}"
      storage:
        type: static
        static:
          pvcName: home-nfs
          subPath: "home/hub.pangeo.io/{username}"
      cloudMetadata:
        enabled: true
      cpu:
        limit: 4
        guarantee: 1
      memory:
        limit: 14G
        guarantee: 4G

    hub:
      resources:
        requests:
          cpu: "0.25"
          memory: 0.5Gi
        limits:
          cpu: "1.25"
          memory: 1Gi
      extraConfig:
        profile_list: |
          c.KubeSpawner.profile_list = [
            {
                'display_name': 'small (n1-highmem-2 | 2 cores, 12GB)',
                'kubespawner_override': {
                    'cpu_limit': 2,
                    'cpu_guarantee': 2,
                    'mem_limit': '12G',
                    'mem_guarantee': '12G',
                }
            },
            {
                'display_name': 'standard (n1-highmem-4 | 4 cores, 24GB)',
                'kubespawner_override': {
                    'cpu_limit': 4,
                    'cpu_guarantee': 4,
                    'mem_limit': '24G',
                    'mem_guarantee': '24G',
                }
            }
          ]

        customPodHook: |
          c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
          c.JupyterHub.template_vars = {
            'pangeo_hub_title': 'hub.pangeo.io',
            'pangeo_hub_subtitle': 'a community hub for geoscience research',
            'pangeo_welcome': """Welcome to hub.pangeo.io. This hub lives in Google Cloud region <code>us-central1-b</code>. It is maintained by the <a href="http://pangeo.io">Pangeo project</a> and supported by a grant from the National Science Foundation (NSF award 1740648), which includes a direct award of cloud credits from Google Cloud. The hub's configuration is stored in the github repository <a href="https://github.com/pangeo-data/pangeo-cloud-federation/">https://github.com/pangeo-data/pangeo-cloud-federation/</a>. To provide feedback and report any technical problems, please use the <a href="https://github.com/pangeo-data/pangeo-cloud-federation//issues">github issue tracker</a>."""
          }

      extraVolumes:
        - name: custom-templates
          gitRepo:
            repository: "https://github.com/pangeo-data/pangeo-custom-jupyterhub-templates.git"
            revision: "0c799bb2f880c8b516dcf90e2a90328078d60c25"
      extraVolumeMounts:
        - mountPath: /usr/local/share/jupyterhub/custom_templates
          name: custom-templates
          subPath: "pangeo-custom-jupyterhub-templates/templates"
        - mountPath: /usr/local/share/jupyterhub/static/extra-assets
          name: custom-templates
          subPath: "pangeo-custom-jupyterhub-templates/extra-assets"

      extraEnv:
        OAUTH2_AUTHORIZE_URL: "https://pangeo.auth0.com/authorize"
        OAUTH2_TOKEN_URL: "https://pangeo.auth0.com/oauth/token"
        OAUTH_CALLBACK_URL: "https://staging.hub.pangeo.io/hub/oauth_callback"

    auth:
      type: custom
      custom:
        className: oauthenticator.generic.GenericOAuthenticator
        config:
          login_service: "auth0"
          token_url: https://pangeo.auth0.com/oauth/token
          userdata_url: https://pangeo.auth0.com/oauth/userinfo
          userdata_method: GET
          username_key: nickname
      admin:
        access: true
        users:
          - jhamman
          - rabernat
homeDirectories:
  nfs:
    enabled: true
    serverPath: "/homes"
    # Output from gcloud beta filestore instances describe dev-home --location=us-central1-b
    serverIP: 10.171.161.186
    serverName: test
