pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
        - staging.hub.pangeo.io
        letsencrypt:
          contactEmail: jhamman@ucar.edu
      service:
        loadBalancerIP: 35.232.186.70
    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 0.25Gi
    scheduling:
      userScheduler:
        enabled: false

gateway:
  clusterManager:
    image:
      name: pangeo/pangeo-notebook-onbuild
      tag: 2019.09.23
      pullPolicy: IfNotPresent

    clusterStartTimeout: 600
    workerStartTimeout: 600
    worker:
      extraPodConfig:
        tolerations:
          - key: "k8s.dask.org_dedicated"
            operator: "Equal"
            value: "worker"
    scheduler:
      extraPodConfig:
        tolerations:
          - key: "k8s.dask.org_dedicated"
            operator: "Equal"
            value: "worker"

  auth:
    type: jupyterhub
    jupyterhub:
      apiUrl: https://staging.hub.pangeo.io/hub/api/
