pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - staging.hub.pangeo.io
        letsencrypt:
          contactEmail: jhamman@ucar.edu
      service:
        loadBalancerIP: 35.232.186.70
    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 0.25Gi
    scheduling:
      userScheduler:
        enabled: false
    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://staging.hub.pangeo.io/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-dev-staging-dask-gateway.dev-staging:80"
    hub:
      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: "http://traefik-dev-staging-dask-gateway.dev-staging"
