name: Build AWS Image
on:
  push:
    branches:
      - staging
      #- prod
    paths:
      - 'deployments/icesat2/image/binder/*'
      - '.github/workflows/build-aws-image.yaml'
  pull_request:
    branches:
      - staging
      #- prod
    paths:
      - 'deployments/icesat2/image/binder/*'
      - '.github/workflows/build-aws-image.yaml'

jobs:
  build_aws_image:
    name: Build AWS Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker://yuvipanda/hubploy:20200826083951674280
        name: Build & Push AWS Image if Needed
        with:
          args: build icesat2 --push
